added printgitdir

diff --git a/config/aliases b/config/aliases
--- a/config/aliases
+++ b/config/aliases
@@ -163,34 +163,57 @@ function pac() {
 }
 
 function pacr() {
-    PACS=$(pacman -Q | fzf -m --preview="pacman -Qi {}")
-    (($?)) || xargs -a <(echo $PACS) sudo pacman -R
+    PACS=$(pacman -Q | fzf -m --preview="pacman -Qi {1}")
+    (($?)) || xargs -a <(echo $PACS | cut -d' ' -f1) sudo pacman -R
 }
 
 function pacl() {
     pacman -Q | fzf -m --preview="pacman -Qi {1}"
 }
- 
+
 function ex () {
-  if [ -f "$1" ] ; then
-    case $1 in
-      *.tar.bz2)   tar xjf $1   ;;
-      *.tar.gz)    tar xzf $1   ;;
-      *.bz2)       bunzip2 $1   ;;
-      *.rar)       unrar x $1   ;;
-      *.gz)        gunzip $1    ;;
-      *.tar)       tar xf $1    ;;
-      *.tbz2)      tar xjf $1   ;;
-      *.tgz)       tar xzf $1   ;;
-      *.zip)       unzip $1     ;;
-      *.Z)         uncompress $1;;
-      *.7z)        7z x $1      ;;
-      *.deb)       ar x $1      ;;
-      *.tar.xz)    tar xf $1    ;;
-      *.tar.zst)   unzstd $1    ;;
-      *)           echo "'$1' cannot be extracted via ex()" ;;
-    esac
-  else
-    echo "'$1' is not a valid file"
-  fi
+    if [ -f "$1" ] ; then
+        case $1 in
+            *.tar.bz2)   tar xjf $1   ;;
+            *.tar.gz)    tar xzf $1   ;;
+            *.bz2)       bunzip2 $1   ;;
+            *.rar)       unrar x $1   ;;
+            *.gz)        gunzip $1    ;;
+            *.tar)       tar xf $1    ;;
+            *.tbz2)      tar xjf $1   ;;
+            *.tgz)       tar xzf $1   ;;
+            *.zip)       unzip $1     ;;
+            *.Z)         uncompress $1 ;;
+            *.7z)        7z x $1      ;;
+            *.deb)       ar x $1      ;;
+            *.tar.xz)    tar xf $1    ;;
+            *.tar.zst)   unzstd $1    ;;
+            *)           echo "'$1' cannot be extracted via ex()" ;;
+        esac
+    else
+        echo "'$1' is not a valid file"
+    fi
+}
+
+function printgitdir () {
+    if [[ $# -eq 1 ]]; then
+        if [[ -f "$1" ]]; then
+            path=$(dirname $1)
+        else
+            path=$1
+        fi
+        _root_dir="$(git -C $path rev-parse --show-toplevel 2>/dev/null)"
+        if [[ $? -gt 0 ]]; then
+            echo $path
+        else
+            echo $_root_dir
+        fi
+    else
+        _root_dir="$(git rev-parse --show-toplevel 2>/dev/null)"
+        if [[ $? -gt 0 ]]; then
+            pwd
+        else
+            echo $_root_dir
+        fi
+    fi
 }
